### PR TITLE
Update infoblox.py

### PR DESCRIPTION
**Pull request by tapanswain**
def create_host_record  function, func:nextavailableip need network reference . you can call get_next_available_ip function to get free ip

### CODE REVIEW

**Comment by tapanswain** [comment]
def create_host_record function, func:nextavailableip need network reference . you can call get_next_available_ip function to get free ip

**Comment by igor-feoktistov** [comment]
Which version WAPI you are running? In WAPI 1.6 it does not require network reference.

**Comment by tapanswain** [comment]
Thanks for your quick response here. we are using 1.0 version, so it is not working . 
Can we add functionality to as per wapi version we use  functions ?

**Comment by igor-feoktistov** [comment]
For WAPI 1.0 you can still use the same library with two calls:
1. get_next_available for network2. create_host_record with obtained in step #1 IP
No patch needed.

**Comment by tapanswain** [comment]
two issue when we use 1,0 
1)Invalid value for ipv4addr: "func:nextavailableip:x.x.x.x/y": Invalid IPv4 address , 
2)Unknown argument: _return_fields=['ipv4addrs']

**Pull request closed without merging**
